#ORIGIN
LIFERAY_MARKETPLACE_ORIGIN_OAUTH_CLIENT_ID=id-b47b6f30-a3c4-674f-28a9-5135948a6c20
LIFERAY_MARKETPLACE_ORIGIN_OAUTH_CLIENT_SECRET=secret-8f3e54f4-65af-1ad3-2a6f-1c3b565e6bfc
LIFERAY_MARKETPLACE_ORIGIN_URL=https://www-uat.liferay.com/
LIFERAY_MARKETPLACE_ORIGIN_MARKETPLACE_SITE_GROUP_ID=448812852
LIFERAY_MARKETPLACE_ORIGIN_GLOBAL_SITE_GROUP_ID=10195
LIFERAY_MARKETPLACE_ORIGIN_BUNDLED_CATEGORY_ID=449928372
LIFERAY_MARKETPLACE_ORIGIN_SOLUTION_CATEGORY_ID=449736583

#DESTINATION
LIFERAY_MARKETPLACE_DESTINATION_OAUTH_CLIENT_ID=id-39f12af0-3187-c135-fa23-8af4af52088
LIFERAY_MARKETPLACE_DESTINATION_OAUTH_CLIENT_SECRET=secret-2d981653-ce9d-f6aa-2738-8fa96e602a
LIFERAY_MARKETPLACE_DESTINATION_URL=http://localhost:18080/
LIFERAY_MARKETPLACE_DESTINATION_MARKETPLACE_SITE_GROUP_ID=36995
LIFERAY_MARKETPLACE_DESTINATION_GLOBAL_SITE_GROUP_ID=20121