#
# Application
#

liferay.marketplace.etc.spring.boot.url=http://localhost:58081

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-marketplace-etc-cron-oahs.oauth2.headless.server.client.secret=secret-bd81c0b8-dd64-af1c-3a7d-16df5ebc19
liferay.oauth.application.external.reference.codes=liferay-marketplace-etc-cron-oahs