#
# Application
#

liferay.partner.koroneiki.auth.token=
liferay.partner.koroneiki.auth.url=
liferay.partner.koroneiki.server.protocol=https

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:18080
com.liferay.lxc.dxp.mainDomain=localhost:18080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-partner-koroneiki-cron-oauth-application-headless-server.oauth2.headless.server.client.secret=secret-e0b4cd7b-3528-6b3c-1941-f2199382232
liferay.oauth.application.external.reference.codes=liferay-partner-koroneiki-cron-oauth-application-headless-server
liferay.oauth.urls.excludes=/ready