#
# Application
#

liferay.learn.dxp.site.group.id=10182
liferay.learn.webassessor.security.token=am4iWDw3

#
# LXC
#

com.liferay.lxc.dxp.domains=www-uat.liferay.com
com.liferay.lxc.dxp.mainDomain=www-uat.liferay.com
com.liferay.lxc.dxp.server.protocol=https

#
# OAuth
#

<<<<<<< HEAD
liferay-learn-etc-spring-boot-oauth-application-headless-server.oauth2.headless.server.client.secret=myfancypassword

liferay.oauth.application.external.reference.codes=\
    liferay-learn-etc-spring-boot-oauth-application-headless-server,\
    liferay-learn-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=/ready
=======
liferay.oauth.application.external.reference.codes=liferay-learn-etc-spring-boot-oauth-application-user-agent
liferay.oauth.urls.excludes=/ready,/documents-and-media/download
>>>>>>> 7ec1e30 (LRSD-8509 -  Updating files and fixing bugs)

#
# Spring Boot
#

server.port=58081