components:
    schemas:
        TestrayCaseResultComparison:
            properties:
                blocked:
                    type: object
                didNotRun:
                    type: object
                failed:
                    type: object
                passed:
                    type: object
                testFix:
                    type: object
            type: object
        TestrayComparison:
            properties:
                testrayComponentComparisons:
                    items:
                        $ref: "#/components/schemas/TestrayComponentComparison"
                    type: array
                testrayRunComparison:
                    $ref: "#/components/schemas/TestrayCaseResultComparison"
                testrayTeamComparisons:
                    items:
                        $ref: "#/components/schemas/TestrayTeamComparison"
                    type: array
            type: object
        TestrayComponentComparison:
            properties:
                name:
                    type: string
                testrayCaseResultComparison:
                    $ref: "#/components/schemas/TestrayCaseResultComparison"
            type: object
        TestrayTeamComparison:
            properties:
                name:
                    type: string
                testrayCaseResultComparison:
                    $ref: "#/components/schemas/TestrayCaseResultComparison"
            type: object
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Testray REST"
    version: v1.0
openapi: 3.0.1
paths:
    "/testray-run-comparisons/{testrayRunId1}/{testrayRunId2}":
        get:
            operationId: getTestrayRunComparisonTestrayRunId1TestrayRunId2
            parameters:
                - in: path
                  name: testrayRunId1
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: testrayRunId2
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: testrayCasePriorities
                  schema:
                      type: string
                - in: query
                  name: testrayTeamId
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TestrayComparison"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/TestrayComparison"
            tags: ["TestrayComparison"]